# Generated by Django 4.2.30 on 2026-08-16 19:09

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postattachment'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('porra', django.db.models.manager.Manager()),
            ],
        ),
    ]
