# Generated by Django 4.2.30 on 2026-08-17 14:49

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('obj1', django.db.models.manager.Manager()),
            ],
        ),
    ]
